[project]
name = "grclpr"
version = "0.1.0"
description = ""
authors = [
    {name = "Yaniv Shulman",email = "yaniv@shulman.info"}
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "rsklpr (>=2.0.0,<3.0.0)",
    "matplotlib (>=3.10.7,<4.0.0)",
    "networkx (>=3.5,<4.0)",
    "notebook (>=7.4.7,<8.0.0)",
    "scikit-learn (>=1.7.2,<2.0.0)",
    "numpy (>=2.3.4,<3.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "joblib (>=1.5.2,<2.0.0)",
    "cartopy (>=0.25.0,<0.26.0)"
]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
black = {extras = ["jupyter"], version = "^26.3.1"}
scipy-stubs = "^1.17.1.4"
pytest-xdist = "^3.8.0"
pandas-stubs = "^3.0.0.260204"
mypy = "^1.20.1"
ruff = "^0.15.10"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".idea",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pycache__",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "paper",
    "venv",
]

# Same as Black.
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-ra -q --strict-markers"
markers = [
    "slow: tests that take a long time to run",
]
minversion = "6.0"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
omit = ["tests/*"]

[tool.coverage.report]
show_missing=true